from __future__ import annotations

from typing import Any


def run_fake_agent(context: dict[str, Any]) -> str:
    """Fake diagnostic agent that produces a deterministic report from context.

    Used for testing without any LLM dependency.
    """
    lines = [
        "# Diagnostic Agent Report (Fake)",
        "",
        "## Episode Under Review",
        f"- Episode ID: {context.get('episode_id', 'unknown')}",
        "",
        "## Safety Summary",
        f"- Total Steps: {context.get('total_steps', 0)}",
        f"- Approved: {context.get('approved_steps', 0)}",
        f"- Blocked: {context.get('blocked_steps', 0)}",
        f"- Rejected: {context.get('rejected_steps', 0)}",
        f"- Manual Review: {context.get('manual_review_steps', 0)}",
        f"- Min Clearance: {context.get('min_clearance', 'N/A')}",
        "",
        "## Critical Steps Identified",
        "",
    ]
    for step in context.get("critical_steps", []):
        lines.append(
            f"- Step {step.get('step_index', '?')}: {step.get('decision', '?')} "
            f"(clearance: {step.get('min_clearance', '?')})"
        )
    lines.append("")
    lines.append("## Boundary Statement")
    lines.append("")
    lines.append("This report is generated by a diagnostic-only assistant.")
    lines.append("No robot actions were approved, rejected, modified, or executed.")
    lines.append("")
    return "\n".join(lines)
